Христофрова Полина Андреевна

Notes:
Я добавила префикс "tmp_*" на все временные файлы и папки (requirements.txt | venv | etc.), чтобы срабатывал .gitignore

# Task 1. Генерация сетки координат

In [3]:
import numpy as np

In [16]:
arr1 = np.arange(-5, 6, 1)
arr2 = np.arange(-5, 6, 1)

x, y = np.meshgrid(arr1, arr2)

z = x**2 + y**2

display(x)
display(y)
display(z)

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5]])

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

array([[50, 41, 34, 29, 26, 25, 26, 29, 34, 41, 50],
       [41, 32, 25, 20, 17, 16, 17, 20, 25, 32, 41],
       [34, 25, 18, 13, 10,  9, 10, 13, 18, 25, 34],
       [29, 20, 13,  8,  5,  4,  5,  8, 13, 20, 29],
       [26, 17, 10,  5,  2,  1,  2,  5, 10, 17, 26],
       [25, 16,  9,  4,  1,  0,  1,  4,  9, 16, 25],
       [26, 17, 10,  5,  2,  1,  2,  5, 10, 17, 26],
       [29, 20, 13,  8,  5,  4,  5,  8, 13, 20, 29],
       [34, 25, 18, 13, 10,  9, 10, 13, 18, 25, 34],
       [41, 32, 25, 20, 17, 16, 17, 20, 25, 32, 41],
       [50, 41, 34, 29, 26, 25, 26, 29, 34, 41, 50]])

# Task 2. Создание двумерного массива

In [18]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [19]:
import numpy as np

In [ ]:
try:
    # Create array
    arr = np.arange(1, 10)

    # Reshape array in matrix way
    arr = arr.reshape(3, 3)
    
    # Display array
    display(arr)
except:
    # Print error
    print('Bad reshaping')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
!deactivate

# Task 4. Индексация и срезы

In [25]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [ ]:
import numpy as np

In [29]:
# Create array
arr = np.arange(10, 20)

# Display array
print('Default array:')
display(arr)

# Display slice from 3 to 7 (included)
print('Sliced array:')
display(arr[3:8])

# Refresh elems from 5 to 8
arr[5:8] = 0

# Display array
print('Modifed array:')
display(arr)

Default array:


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Sliced array:


array([13, 14, 15, 16, 17])

Modifed array:


array([10, 11, 12, 13, 14,  0,  0,  0, 18, 19])

In [ ]:
!deactivate

# Task 5. Математические операции

In [30]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip install logging
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [31]:
import logging
import numpy as np

In [32]:
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)

In [33]:
# Create arrays
a = np.arange(1, 6)
b = np.arange(5, 0, -1)

print('Default arrays:')
display(a)
display(b)

try:
    # Lets calculate math operations
    sum_arr = a + b
    diff_arr = a - b
    prod_arr = a * b
    div_arr = a / b

    # Display result arrays
    print('Sum array:')
    display(sum_arr)

    print('Diff array:')
    display(diff_arr)

    print('Prod array:')
    display(prod_arr)

    print('Div array:')
    display(div_arr)

    logging.info('Success calculation')

except:
    # Print error
    logging.error('Be carefull the arrays valid and without div to zero')

Default arrays:


array([1, 2, 3, 4, 5])

array([5, 4, 3, 2, 1])

Sum array:


array([6, 6, 6, 6, 6])

Diff array:


array([-4, -2,  0,  2,  4])

Prod array:


array([5, 8, 9, 8, 5])

Div array:


array([0.2, 0.5, 1. , 2. , 5. ])

INFO: Success calculation


In [ ]:
!deactivate

# Task 6. Решите системы линейных уравнений

In [34]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [35]:
import numpy as np

In [39]:
# Create arrays
A = np.array([[2, 1], [1, -1]])
b = np.array([5, 1])

try:
    # Lets calculate
    result = np.linalg.solve(A, b)

    # Display result array
    display(result)

    logging.info('Success calculation')

except:
    # Print error
    logging.error('Singular matrix')

array([2., 1.])

INFO: Success calculation


In [ ]:
!deactivate

# Task 8. Соединение массивов

In [40]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip install logging
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [41]:
import logging
import numpy as np

In [42]:
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)

In [59]:
# Create arrays
a = np.arange(1, 4)
b = np.arange(4, 7)

print('Default arrays:')
display(a)
display(b)

try:
    # Lets concatinate
    concat_by_rows = np.hstack((a, b))

    concat_by_columns = np.concatenate(
        (a.reshape(a.shape[0], 1),
        b.reshape(b.shape[0], 1)),
        axis=1
    )

    print('Display concated arrays:')
    display(concat_by_rows)
    display(concat_by_columns)

    logging.info('Success concatination')

except:
    # Print error
    logging.error('Something wrong')

Default arrays:


array([1, 2, 3])

array([4, 5, 6])

Display concated arrays:


array([1, 2, 3, 4, 5, 6])

array([[1, 4],
       [2, 5],
       [3, 6]])

INFO: Success concatination


In [ ]:
!deactivate

# Task 11. Нормализация массива

In [60]:
!python -m venv tmp_venv
!source tmp_venv/bin/activate
!pip install numpy
!pip install logging
!pip freeze > tmp_requirements.txt


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [61]:
import logging
import numpy as np

In [62]:
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)

In [76]:
# Define random state
np.random.seed(42)

# Generate array
arr = np.random.randint(0, 100, 10)

print('Default array:')
display(arr)

try:
    # Lets normalize
    normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

    print('Normalized array:')
    display(normalized)

    logging.info('Success concatination')

except:
    # Print error
    logging.error('Something wrong')

Default array:


array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

Normalized array:


array([0.47435897, 1.        , 0.        , 0.73076923, 0.58974359,
       0.07692308, 0.87179487, 0.92307692, 0.76923077, 0.76923077])

INFO: Success concatination


In [ ]:
!deactivate